---
title: "Rankings Viz"
author: "Group E"
date: "12/11/2021"
output: pdf_document
---
```{r}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r echo = FALSE}
library(tidyverse)
# Here is another way to load the datasets:

data_URLs <- paste("https://raw.githubusercontent.com/JeffSackmann/tennis_wta/master/wta_matches_",
                   1968:2021,
                   ".csv", 
                   sep = "")
wtaresults <- read_csv(data_URLs)

data_URLs2 <- paste("https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_matches_",
                    1968:2021,
                    ".csv", 
                    sep = "")
atpresults <- read_csv(data_URLs2)
```

```{r echo = FALSE}
# adding column to prepare to combine datasets
wtaresults <- wtaresults %>%
  mutate(tour = "WTA") 

atpresults <- atpresults %>%
  mutate(tour = "ATP")

# moving tour column to front for ease
wtaresults <- wtaresults[,c(50,1:49)]
atpresults <- atpresults[,c(50,1:49)]

# combining the datasets
tennis_results <- rbind(wtaresults, atpresults)

# making date objects from date
library(lubridate)
tennis_results <- tennis_results %>%
  mutate(tourney_date = ymd(tourney_date)) %>%
  mutate(year = year(tourney_date)) %>%
  mutate(month = month(tourney_date))

# reorganizing date columns together
tennis_results <- tennis_results[,c(1:7,51:52,8:50)]
```

```{r cleaning data, include = FALSE}
# ensuring that `winner_seed` is of numeric type instead of character
tennis_results <- tennis_results %>% 
  mutate(winner_seed = as.integer(winner_seed)) %>%
  mutate(loser_seed = as.integer(loser_seed))

# making `winner_entry` and `loser_entry` abbreviations consistent
tennis_results <- tennis_results %>% 
  mutate(loser_entry = case_when(
    winner_entry == 'Alt' ~ 'ALT',
    loser_entry == 'A' ~ 'ALT',
    loser_entry == 'Alt' ~ 'ALT',
    loser_entry == 'wc' ~ 'WC',
    loser_entry == 'S' ~ 'SE',
    TRUE ~ loser_entry
  ))

# cleaning datasets with duplicated information
clean_1973_surbiton <- tennis_results %>%
  filter(tourney_id == '1973-1098',
         match_num != 32,
         match_num != 33)

clean_1981_johannesburg <- tennis_results %>% 
  filter(tourney_id == '1981-1099') %>%
  slice_tail(n = 11)

clean_1990_taranto <- tennis_results %>% 
  filter(tourney_id == '1990-W-WT-ITA-01A-1990',
         !(match_num == 29 & round == 'R32'),
         !(match_num == 30 & round == 'R32'),
         !(match_num == 31 & round == 'R32'),
         match_num <= 31)

clean_1991_stpetersburg <- tennis_results %>% 
  filter(tourney_id == '1991-W-WT-URS-01A-1991',
         !(match_num == 29 & round == 'R32'),
         !(match_num == 30 & round == 'R32'),
         !(match_num == 31 & round == 'R32'),
         match_num <= 31)

clean_1991_oakland <- tennis_results %>% 
  filter(tourney_id == '1991-W-WT-USA-19A-1991') %>%
  slice_head(n = 27)

clean_1992_oklahoma <- tennis_results %>% 
  filter(tourney_id == '1992-W-WT-USA-02A-1992',
         !(match_num == 28 & round == 'R32'),
         !(match_num == 29 & round == 'R32'),
         !(match_num == 30 & round == 'R32'),
         !(match_num == 31 & round == 'R32'),
         match_num <= 31)

# vector of RR tourneys or tourneys with duplicated information
duplicated_tourneys <- c('1973-1098', '1970-9205', '1981-1099',
                         '1990-W-WT-ITA-01A-1990', '1991-W-WT-URS-01A-1991', 
                         '1991-W-WT-USA-19A-1991', '1992-W-WT-USA-02A-1992')

tennis_results <- tennis_results %>% 
  filter(!(str_detect(tourney_id, "-615") | str_detect(tourney_id, "-8888")), 
         !(tourney_id %in% duplicated_tourneys)) %>%
  rbind(clean_1973_surbiton, clean_1981_johannesburg, 
        clean_1990_taranto, clean_1991_stpetersburg, 
        clean_1991_oakland, clean_1992_oklahoma)

# replacing mistaken entries
tennis_results[26765,13] = NA
tennis_results[26765,12] = 6
tennis_results[43756,12] = 9
# from looking at the original draw
# https://wtafiles.blob.core.windows.net/pdf/draws/archive/1983/702.pdf
# it can be deduced that they meant seed 9 instead of seed 96

# removing junior, challenger, exho results
# they are not the main pro tour
tennis_results <- tennis_results %>%
  filter(tourney_level != "J" & tourney_level != "CC" & tourney_level != "E")

# standardizing heights to cm
tennis_results <- tennis_results %>%
  mutate(winner_ht = ifelse(winner_ht < 100, winner_ht * 100, winner_ht),
         loser_ht = ifelse(loser_ht < 100, loser_ht * 100, loser_ht))

# adding a column of overall tournament winners for each match
winners <- tennis_results %>%
  filter(round == 'F') %>%
  mutate(tourney_winner = winner_name) %>%
  select(tour:month, tourney_winner)
tennis_results <- tennis_results %>%
  left_join(winners)
```

```{r wta rank}
library(readr)
rank_URLs <- c("https://raw.githubusercontent.com/JeffSackmann/tennis_wta/master/wta_rankings_90s.csv",
               "https://raw.githubusercontent.com/JeffSackmann/tennis_wta/master/wta_rankings_00s.csv",
               "https://raw.githubusercontent.com/JeffSackmann/tennis_wta/master/wta_rankings_10s.csv",
               "https://raw.githubusercontent.com/JeffSackmann/tennis_wta/master/wta_rankings_20s.csv",
               "https://raw.githubusercontent.com/JeffSackmann/tennis_wta/master/wta_rankings_current.csv")
wtarank <- read_csv(rank_URLs) 
```

```{r atp rank}
# 20s file is missing first row with variable names so loaded separately
atp_rankings_90s <- read_csv("https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_rankings_90s.csv")
atp_rankings_00s <- read_csv("https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_rankings_00s.csv")
atp_rankings_10s <- read_csv("https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_rankings_10s.csv")
atp_rankings_20s <- read_csv("https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_rankings_20s.csv", 
    col_names = FALSE)
colnames(atp_rankings_20s) <- c("ranking_date", "rank", "player", "points")
atp_rankings_current <- read_csv("https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_rankings_current.csv")
atprank <- rbind(atp_rankings_90s,
                 atp_rankings_00s,
                 atp_rankings_10s,
                 atp_rankings_20s,
                 atp_rankings_current)
```

```{r combining data}
library(tidyverse)
# adding column to prepare to combine datasets
wtarank <- wtarank %>%
  mutate(tour = "WTA") 

atprank <- atprank %>%
  mutate(tours = NA, tour = "ATP")

# moving tour column to front for ease
wtarank <- wtarank[,c(6,5,1:4)]
atprank <- atprank[,c(5,6,1:4)]

# combining the datasets
tennis_rankings <- rbind(wtarank, atprank)

# making date objects from date
library(lubridate)
tennis_rankings <- tennis_rankings %>%
  mutate(ranking_date = ymd(ranking_date)) %>%
  mutate(year = year(ranking_date)) %>%
  mutate(month = month(ranking_date)) %>%
  mutate(week = week(ranking_date))
 
# reorganizing date columns together
tennis_rankings <- tennis_rankings[,c(1:3,7:9,4:6)]
```

```{r}
# source: https://en.wikipedia.org/wiki/ATP_Rankings
atp_active_top10 <- tennis_results %>%
  filter(winner_name == "Roger Federer" |
         winner_name == "Rafael Nadal" |
         winner_name == "Novak Djokovic" |
         winner_name == "Andy Murray" |
         winner_name == "Daniil Medvedev" |
         winner_name == "Stan Wawrinka" |
         winner_name == "Milos Raonic" |
         winner_name == "Alexander Zverev" |
         winner_name == "Grigor Dimitrov" |
         winner_name == "Marin Cilic" |
         winner_name == "Juan Martin del Potro" |
         winner_name == "Dominic Thiem" |
         winner_name == "Stefanos Tsitsipas" |
         winner_name == "Kei Nishikori") %>%
  group_by(winner_name) %>%
  summarize(winner_id = mean(winner_id)) %>%
  pull(winner_id)

# source: https://en.wikipedia.org/wiki/WTA_Rankings
wta_active_top10 <- tennis_results %>%
  filter(winner_name == "Venus Williams" |
         winner_name == "Serena Williams" |
         winner_name == "Victoria Azarenka" |
         winner_name == "Angelique Kerber" |
         winner_name == "Karolina Pliskova" |
         winner_name == "Garbine Muguruza" |
         winner_name == "Simona Halep" |
         winner_name == "Naomi Osaka" |
         winner_name == "Ashleigh Barty" |
         winner_name == "Svetlana Kuznetsova" |
         winner_name == "Vera Zvonareva" |
         winner_name == "Petra Kvitova" |
         winner_name == "Aryna Sabalenka" |
         winner_name == "Elina Svitolina" |
         winner_name == "Sloane Stephens" |
         winner_name == "Barbora Krejcikova") %>%
  group_by(winner_name) %>%
  summarize(winner_id = mean(winner_id)) %>%
  pull(winner_id)
```

```{r, include = FALSE, eval = FALSE}
 |
         winner_name == "Tommy Robredo" |
         winner_name == "Jo-Wilfried Tsonga" |
         winner_name == "Kevin Anderson" |
         winner_name == "Andrey Rublev" |
         winner_name == "Gilles Simon" |
         winner_name == "Gael Monfils" |
         winner_name == "Richard Gasquet" |
         winner_name == "Fernando Verdasco" |
         winner_name == "David Goffin" |
         winner_name == "Matteo Berrettini" |
         winner_name == "Jack Sock" |
         winner_name == "John Isner" |
         winner_name == "Karen Khachanov" |
         winner_name == "Diego Schwartzman" |
         winner_name == "Casper Ruud" |
         winner_name == "Fabio Fognini" |
         winner_name == "Roberto Bautista Agut" |
         winner_name == "Jannik Sinner" |
         winner_name == "Hubert Hurkacz" |
         winner_name == "Ernests Gulbis" |
         winner_name == "Pablo Carreno Busta" |
         winner_name == "Lucas Pouille" |
         winner_name == "Denis Shapovalov" |
         winner_name == "Felix Auger Aliassime"

 |
         winner_name == "Samantha Stosur" |
         winner_name == "Caroline Garcia" |
         winner_name == "Bianca Andreescu" |
         winner_name == "Belinda Bencic" |
         winner_name == "Sofia Kenin" |
         winner_name == "Iga Swiatek"|
         winner_name == "Sara Errani" |
         winner_name == "Eugenie Bouchard" |
         winner_name == "Jelena Ostapenko" |
         winner_name == "Maria Sakkari" |
         winner_name == "Madison Keys" |
         winner_name == "Ons Jabeur" |
         winner_name == "Anett Kontaveit" |
         winner_name == "Paula Badosa" |
         winner_name == "Andrea Petkovic" |
         winner_name == "Coco Vandeweghe" |
         winner_name == "Kristina Mladenovic" |
         winner_name == "Darya Kasatkina"
```

```{r}
tennis_rankings <- tennis_rankings %>%
  group_by(player) %>%
  mutate(top10 = ifelse(rank <= 10,1,0)) %>%
  mutate(weeks_top10 = cumsum(top10)) %>%
  select(-top10) %>%
  mutate(image = player) %>%
  mutate(image = case_when(
    image == 200748 ~ "https://photoresources.wtatennis.com/photo-resources/2019/10/08/f1dd1872-bfaa-4b82-bb17-ae91a3ebf2bb/WazfwVSd.png?width=950",
    image == 201493 ~ "https://photoresources.wtatennis.com/photo-resources/2019/10/08/8762852b-5a86-414d-87ee-2efad80d4e64/tfkMNfJw.png?width=950",
    image == 214544 ~ "https://photoresources.wtatennis.com/photo-resources/2020/09/30/077d0d47-22d6-4efc-b3a9-e13ff64b0934/Sabalenka_Hero-Smile.png?width=950",
    image == 202458 ~ "https://photoresources.wtatennis.com/photo-resources/2020/09/30/d05d8377-816c-4499-bc48-5e307c893cc7/Barty_Hero-Smile.png?width=950",
    image == 206252 ~ "https://photoresources.wtatennis.com/photo-resources/2020/09/30/51357b9f-48f7-48ab-948a-f86e07e5dae6/Krejcikova_Hero-Smile.png?width=950",
    image == 202494 ~ "https://photoresources.wtatennis.com/photo-resources/2021/01/12/d3ab2f03-ce4c-483f-9174-97b29d0bed3d/Svitolina_Hero-Smile.png?width=950",
    image == 202469 ~ "https://photoresources.wtatennis.com/photo-resources/2020/09/30/58137bc5-55f4-44aa-9260-e9c39d644c36/Muguruza_Hero-Smile.png?width=950",
    image == 201662 ~ "https://photoresources.wtatennis.com/photo-resources/2020/09/30/d2107552-9555-4c17-9eab-6361b940905e/Pliskova_Hero-Smile.png?width=950",
    image == 211768 ~ "https://photoresources.wtatennis.com/photo-resources/2021/01/19/f5e01763-eee7-449f-999a-dcee1011c20e/Osaka_Hero-Smile.png?width=950",
    image == 201520 ~ "https://photoresources.wtatennis.com/photo-resources/2020/09/30/1dfdc52b-00e3-471e-8940-3fa228a32117/Kvitova_Hero-Smile.png?width=950",
    image == 200033 ~ "https://images.prismic.io/fft-rg-site/49fc0008-a476-4f43-bb69-aab6ac17686b_20200120_PJ_WilliamsSerena_US.png?auto=compress,format&rect=0,0,1080,1080&w=300&h=300",
    image == 201594 ~ "https://photoresources.wtatennis.com/photo-resources/2019/10/08/62ecc4f9-a397-4c6f-9c8c-cea093c5ee9c/WzQOhOCP.png?width=950",
    image == 201585 ~ "https://photoresources.wtatennis.com/photo-resources/2019/10/08/988ba546-3bc0-4daf-a768-a268d07ff6b1/sMGEHVqN.png?width=950",
    image == 201320 ~ "https://photoresources.wtatennis.com/photo-resources/2020/09/30/ed4fc3a2-b3c7-4c5f-96e0-b0411cb77a72/Kuznetsova_Hero-Smile.png?width=950",
    image == 201329 ~ "https://images.prismic.io/fft-rg-site/b014ce9b-ae08-43e3-8793-de0c4127949c_20190523_PJ_ZvonarevaVera_US.png?auto=compress,format&rect=0,0,1080,1080&w=300&h=300",
    image == 201458 ~ "https://photoresources.wtatennis.com/photo-resources/2019/10/08/1ab771d9-a81c-4f8d-9e1e-195dd12828b2/dqJqbgIh.png?width=950",
    image == 103819 ~ "https://www.atptour.com/-/media/tennis/players/head-shot/2020/federer_head_ao20.png",
    image == 104925 ~ "https://www.atptour.com/-/media/tennis/players/head-shot/2019/djokovic_head_ao19.png",
    image == 100644 ~ "https://www.atptour.com/-/media/alias/player-headshot/Z355",
    image == 104918 ~ "https://www.atptour.com/-/media/alias/player-headshot/MC10",
    image == 106421 ~ "https://www.atptour.com/-/media/alias/player-headshot/MM58",
    image == 106233 ~ "https://www.atptour.com/-/media/tennis/players/head-shot/2020/thiem_head_ao20.png",
    image == 105777 ~ "https://www.atptour.com/-/media/alias/player-headshot/D875",
    image == 105223 ~ "https://www.atptour.com/-/media/tennis/players/head-shot/2019/delpotro_head_rome19.png",
    image == 105453 ~ "https://www.atptour.com/-/media/alias/player-headshot/N552",
    image == 105227 ~ "https://www.atptour.com/-/media/alias/player-headshot/C977",
    image == 105683 ~ "https://www.atptour.com/-/media/tennis/players/head-shot/2020/raonic_head_ao20.png",
    image == 104745 ~ "https://www.atptour.com/-/media/tennis/players/head-shot/2020/nadal_head_ao20.png",
    image == 104527 ~ "https://www.atptour.com/-/media/tennis/players/head-shot/2020/wawrinka_head_ao20.png",
    image == 126774 ~ "https://www.atptour.com/-/media/alias/player-headshot/TE51"
  ))
```

```{r}
tennis_rankings <- tennis_rankings %>%
  mutate(name = player) %>%
  mutate(name = case_when(
    name == 200748 ~ "Venus Williams",
    name == 201493 ~ "Angelique Kerber",
    name == 214544 ~ "Aryna Sabalenka",
    name == 202458 ~ "Ashleigh Barty",
    name == 206252 ~ "Barbora Krejcikova",
    name == 202494 ~ "Elina Svitolina",
    name == 202469 ~ "Garbiñe Muguruza",
    name == 201662 ~ "Karolina Pliskova",
    name == 211768 ~ "Naomi Osaka",
    name == 200033 ~ "Serena Williams",
    name == 201520 ~ "Petra Kvitova",
    name == 201594 ~ "Simona Halep",
    name == 201585 ~ "Sloane Stephens",
    name == 201320 ~ "Svetlana Kuznetsova",
    name == 201329 ~ "Vera Zvonareva",
    name == 201458 ~ "Victoria Azarenka",
    name == 103189 ~ "Roger Federer",
    name == 104925 ~ "Novak Djokovic",
    name == 100644 ~ "Alexander Zverev",
    name == 104918 ~ "Andy Murray",
    name == 106421 ~ "Daniil Medvedev",
    name == 106233 ~ "Dominic Thiem",
    name == 105777 ~ "Grigor Dimitrov",
    name == 105223 ~ "Juan Martin del Potro",
    name == 105453 ~ "Kei Nishikori",
    name == 105227 ~ "Marin Cilic",
    name == 105683 ~ "Milos Raonic",
    name == 104745 ~ "Rafael Nadal",
    name == 104527 ~ "Stan Wawrinka",
    name == 126774 ~ "Stefanos Tsitsipas"
  ))
```


```{r eval = FALSE}
library(ggimage)
library(gganimate)
library(gifski)
atp_animate <- tennis_rankings %>%
  filter(player %in% atp_active_top10, tour == "ATP") %>%
  mutate(rank = ifelse(rank > 5, NA, rank)) %>%
  ggplot(aes(x = ranking_date, y = rank)) +
  geom_line(aes(color = name)) +
#  geom_segment(aes(xend = ymd("2022-01-01"), yend = rank), linetype = 2) + 
#  geom_text(aes(x = ymd("2022-01-01"), label = name), hjust = 0) +
#  coord_cartesian(clip = 'off') +
#  guides(col = FALSE) +
#  xlim(ymd("2000-01-01"), ymd("2030-01-01")) +
  geom_image(aes(image = image), size = 0.1) +
  scale_y_reverse() +
  guides(col = FALSE) +
  transition_reveal(ranking_date)
final_atp_animate <- animate(atp_animate, fps = 5, renderer = gifski_renderer())
anim_save("final_atp_animate.gif", animation = final_atp_animate, path = "~/Comp Stats/GroupE-tennis/")
```

```{r eval = FALSE}
wta_animate <- tennis_rankings %>%
  filter(player %in% wta_active_top10, tour == "WTA") %>%
  mutate(rank = ifelse(rank > 5, NA, rank)) %>%
  ggplot(aes(x = ranking_date, y = rank)) +
  geom_line(aes(color = name)) +
  geom_image(aes(image = image), size = 0.15) +
  scale_y_reverse() +
  guides(col = FALSE) +
  transition_reveal(ranking_date)
final_wta_animate <- animate(wta_animate, fps = 5, renderer = gifski_renderer())
anim_save("final_wta_animate.gif", animation = final_wta_animate, path = "~/Comp Stats/GroupE-tennis/")
```